[workspace]
members = [
    "chap3",
    "chap4",
    "chap5",
    "chap6",
    "chap7",
    "chap8",
    "chap9",
    "chap10",
    "chap11",
    "chap12",
    "chap13",
    "chap14",
    "chap15",
    "chap16",
]
